name: CI

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - uses: actions-rust-lang/rustfmt@v1

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenCC
        run: |
          sudo apt update
          sudo apt install doxygen cmake wget
          wget https://github.com/BYVoid/OpenCC/archive/refs/tags/ver.1.1.9.tar.gz
          tar xf ver.1.1.9.tar.gz
          cd OpenCC-*
          make -j$(nproc) PREFIX=/usr
          sudo make PREFIX=/usr install
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings

  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        toolchain:
          - stable
          - nightly
        features:
          -
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }} (${{ matrix.features }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install OpenCC
        run: |
          sudo apt update
          sudo apt install doxygen cmake wget
          wget https://github.com/BYVoid/OpenCC/archive/refs/tags/ver.1.1.9.tar.gz
          tar xf ver.1.1.9.tar.gz
          cd OpenCC-*
          make -j$(nproc) PREFIX=/usr
          sudo make PREFIX=/usr install
      - run: sudo ldconfig
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test ${{ matrix.features }}
      - run: cargo doc ${{ matrix.features }}

  MSRV:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        toolchain:
          - "1.74"
        features:
          -
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }} (${{ matrix.features }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install OpenCC
        run: |
          sudo apt update
          sudo apt install doxygen cmake wget
          wget https://github.com/BYVoid/OpenCC/archive/refs/tags/ver.1.1.9.tar.gz
          tar xf ver.1.1.9.tar.gz
          cd OpenCC-*
          make -j$(nproc) PREFIX=/usr
          sudo make PREFIX=/usr install
      - run: sudo ldconfig
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test --lib --bins ${{ matrix.features }}